version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - IMAGE_NAME="imageapi"
      - REPOSITORY_URI=938624271008.dkr.ecr.us-east-1.amazonaws.com/mkdocs
      - IMAGE_TAG=prod_$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo Image_tag $IMAGE_TAG
      - docker build -t mkdocs .
      - docker tag mkdocs:latest 938624271008.dkr.ecr.us-east-1.amazonaws.com/mkdocs:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 938624271008.dkr.ecr.us-east-1.amazonaws.com/mkdocs:latest
      - echo Writing image definitions file...
      
