site_name: Continental ConNext Documentation
dev_addr: '127.0.0.1:8080'
extra_css: ['extra.css']
strict: true
theme:
  name: 'material'
  feature:
    tabs: true
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
nav:
- Wiki: "index.md"
