site_name: Continental Documentation
extra_css: ['extra.css']
strict: true
theme:
  name: 'material'
  feature:
    tabs: true
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
