site_name: Continental Documentation
extra_css: ['extra.css']
strict: true
theme:
  name: 'material'
  feature:
    tabs: true
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
nav:
- Home: "index.md"
- General:
  - Page 1: general/page1.md
- How to:
  - Page 2: how to/page2.md
